### ISSUE TITLE
Request a voxel graphics look

### ISSUE THREAD

**Issue by ghost** [freakyshine/universal-expansion#1]
Hey folks👋🏻

Hows about implementing a voxel like graphic? Probably we could use a unity to threejs transpiler?

Thanks and regards

Timo-cmd

**Comment by danielrlutz** [comment]
Great suggestion!
We'll see if this is the graphics we're looking for in future builds, but for now, this is a good start.
Thanks for your engagement.

Regards,
Daniel

**Comment by danielrlutz** [comment]
I think we have found the graphic type we have been looking for. I appreciate the encourage tho! :) Tell me your opinion about the current graphic style.

I might now close this thread?

Regards,
Daniel
